version: '3.5'

services:
  postgres:
    image: postgres
    container_name: "Canocorean.postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - canocorean-dev
    ports: 
      - "5432:5432"
  canocorean.frontend:
    image: ${DOCKER_REGISTRY-}canocoreanfrontend
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Canocorean.Frontend/Dockerfile
    networks:
      - canocorean-dev
networks:
  canocorean-dev:
    driver: bridge
    name: canocorean-dev