// <auto-generated />
using Canocorean.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Canocorean.Infrastructure.Migrations
{
    [DbContext(typeof(CanocoreanDbContext))]
    partial class CanocoreanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Canocorean.Infrastructure.EntityFramework.Entities.Country", b =>
                {
                    b.Property<string>("ISOCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3);

                    b.HasKey("ISOCode");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            ISOCode = "RU"
                        },
                        new
                        {
                            ISOCode = "US"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
